# Generated by Django 6.0.1 on 2026-01-21 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('pltaform', models.CharField(choices=[('tiktok', 'TikTok'), ('reels', 'Instagram Reels'), ('shorts', 'YouTube Shorts')], max_length=20, verbose_name='Plataforma')),
                ('duration_seconds', models.IntegerField(verbose_name='Duração (segundos)')),
                ('uptade_date', models.DateField(auto_now_add=True, verbose_name='Data de Uplodad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriçãp/Notas')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['-uptade_date'],
            },
        ),
        migrations.CreateModel(
            name='RetentionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_watch_time', models.FloatField(verbose_name='Tempo Médio de Visualização (segundos)')),
                ('retention_score', models.FloatField(verbose_name='Pontuação de Retenção (%)')),
                ('converted', models.BooleanField(default=False, verbose_name='Gerou Conversão/Venda?')),
                ('ai_prediction', models.TextField(blank=True, null=True, verbose_name='Previsão da IA')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.video')),
            ],
            options={
                'verbose_name': 'Métrica de Retenção',
                'verbose_name_plural': 'Métricas de Retenção',
            },
        ),
    ]
