# Generated by Django 6.0.1 on 2026-01-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='pltaform',
            new_name='plataform',
        ),
    ]
