# Generated by Django 6.0.1 on 2026-01-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_pltaform_video_plataform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Vídeo', 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='plataform',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='uptade_date',
            new_name='upload_date',
        ),
    ]
